"""create documents table

Revision ID: 7a2414165b90
Revises: 
Create Date: 2026-09-21 16:33:02.598071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a2414165b90'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='Client-supplied filename, path-sanitised before storage'),
    sa.Column('file_type', sa.String(length=10), nullable=False, comment="Lowercase extension without dot: 'pdf' or 'docx'"),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False, comment='Size of the uploaded file in bytes'),
    sa.Column('char_count', sa.Integer(), nullable=False, comment='Character count of the extracted text'),
    sa.Column('extracted_text', sa.Text(), nullable=False, comment='Full extracted text — not returned in the API response; consumed by M2 chunking'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Ingestion status: extracted | chunking | indexed | error'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp set by the database on INSERT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
